### ISSUE TITLE
Function "get.rooted.tree.height" goes wrong 

### ISSUE THREAD

**Issue by YanHanChen** [snoweye/phyclust#5] opened 2019-09-10 07:49 UTC
Dear Dr. Chen
I'm Yan-Han Chen, a research assistance at Inst. of Stat, NTHU. I have been use your "phyclust" package for phylogenetic analysis, which has brought me much convenience during research. However, I found that function  "get.rooted.tree.height" would go wrong in the case when a tree node has more than 2 (>=3) branches (or say children). After checking your code, I believe that it was resulted by the "if (length(edge.id) == 2)", which should be "if (length(edge.id) >= 2)" instead.
Would it be possible for you to fix it and update this package on CRAN?

**Comment by snoweye** [comment] 2019-09-10 11:19
@YanHanChen Do you have a reproducible example that the function got wrong height for a rooted tree? The function is supposed for the `rooted` tree only.

**Comment by YanHanChen** [comment] 2019-09-10 13:05
@snoweye My apology for not leaving an example. Yes and I can give you the tree I used to find this problem. I think I just leave a newick form tree below. In this example, the tree height should be 325 (it's easy to see this because the tip "Juniperus_oxycedrus" has a branch directly connected to the top node and its length is 325). However, the "get.rooted.tree.height" would render 227.5 since the node "poaceae" has more than 2 branches, which will cause your repeat function to break. If I misunderstand something (like this example is not a rooted tree....,), please let me know. Thank you in advance!
 "((((((Elymus_farctus:97.5,Vulpia_fasciculata:97.5,Ammophila_arenaria:97.5,Cutandia_maritima:97.5,(Bromus_diandrus:48.75,Sporobolus_virginicus:48.75):48.75,Lagurus_ovatus:97.5,Lophocloa_pubescens:97.5)poaceae:48.75,Cyperus_kalli:146.25):48.75,(Asparagus_acutifolius:97.5,Pancratium_maritimum:97.5):97.5):48.75,Smilax_aspera:243.75):48.75,(((((Cakile_maritima:97.5,(Cistus_incanus:48.75,Daphne_gnidium:48.75):48.75)malvales_to_brassicales:48.75,Pistacia_lentiscus:146.25):48.75,((Chamaesyce_peplis:81.25,Euphorbia_terracina:81.25)euphorbiaceae:81.25,((Quercus_ilex:65,Rhamnus_alaternus:65):65,(((Medicago_marina:32.5,Medicago_littoralis:32.5)medicago:32.5,Ononis_variegata:65):32.5,Lotus_cytisoides:97.5):32.5):32.5):32.5):32.5,((((Calystegia_soldanella:97.5,(Plantago_coronopus:65,(Teucrium_flavum:32.5,Prasium_majus:32.5)lamiaceae:32.5):32.5):32.5,(Crucianella_maritima:65,Rubia_peregrina:65)rubiaceae:65):32.5,(((Pseudorlaya_pumila:43.333332,Echinophora_spinosa:43.333332,Eryngium_maritimum:43.333332)apiaceae:43.333332,(Lonicera_implexa:43.333332,Pycnocomon_rutifolium:43.333332)caprifoliaceae:43.333332):43.333336,(((Anthemis_maritima:32.5,Sonchus_bulbosus:32.5):32.5,Centaurea_sphaerocephala:65):32.5,Otanthus_maritimus:97.5,Helichrysum_stoechas:97.5,Phillyrea_angustifolia:97.5)asteraceae:32.5):32.5):32.5,(Polygonum_maritimum:130,(Salsola_kali:65,Silene_canescens:65)NA:65)caryophyllales:65):32.5):32.5,Clematis_flammula:260)eudicots:32.5)poales_to_asterales:32.5,Juniperus_oxycedrus:325)seedplants;"

**Comment by snoweye** [comment] 2019-09-11 02:41
@YanHanChen It is rooted but not a bifurcation one. Could you send an PR to fix the bug? I will merge it and close this issue.

CRAN's submission need to wait because the latest one is only a few days ago unless this is urgent.

**Comment by snoweye** [comment] 2019-09-27 11:13
@YanHanChen 0.1-26 is on CRAN now. Binary files for win and osx would take a few days to show up for download.

**Closed as completed by snoweye** 2019-09-27 11:13 UTC
